  development:
    adapter: postgresql
    database: d84mk0nr4f3o0n
    pool: 5
    username: wejsljihjsxhqv
    password: 7cbb05867cf0ce8c4e7fd156fa0fae77230f22830c26119d812d87b337c5d0ff
    host: ec2-54-246-92-116.eu-west-1.compute.amazonaws.com
